### ISSUE TITLE
An experience with release newer than 2.5?

### ISSUE THREAD

**Issue by nesnera** [aptivate/ckanext-syndicate#7]
I've [installed it at 2.7.0](https://ckan.otevrenamesta.cz/api/util/status) but seems without influence to CKAN behaviour. What is your experience?

BTW: In `/ckanext/syndicate/plugin.py` I changed `from ckan.lib.helpers import asbool` to
```
from ckan.lib.helpers import converters
asbool = converters.asbool
```

**Comment by martinburchell** [comment]
@nesnera so you're saying that you couldn't get the plugin to work with 2.7.0 even after you had made the change to `/ckanext/syndicate/plugin.py` ?

Thanks for reporting the import error. We are already importing toolkit so we can just use toolkit.asbool

**Comment by nesnera** [comment]
`asbool = toolkit.asbool` works well 👍

**Comment by martinburchell** [comment]
@nesnera On the latest CKAN master branch with the `asbool` fix, I see the following stack trace on the celery task when I try to syndicate. Is this what you are seeing?
```

[2017-10-19 17:33:11,426: ERROR/MainProcess] Task syndicate.sync_package[8e630269-2c04-4bd0-99c8-782845b2d3d9-a86ac8f7-891a-4015-a1dd-168eb44a21c3] raised unexpected: RuntimeError('Attempted to generate a URL without the application context being pushed. This has to be executed when application context is available.',)
Traceback (most recent call last):
  File "/usr/lib/ckan_master/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/ckan_master/default/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckanext-syndicate/ckanext/syndicate/tasks.py", line 30, in sync_package_task
    return sync_package(package, action)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckanext-syndicate/ckanext/syndicate/tasks.py", line 120, in sync_package
    params,
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckan/ckan/logic/__init__.py", line 457, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckan/ckan/logic/action/get.py", line 1012, in package_show
    package_dict = model_dictize.package_dictize(pkg, context)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 204, in package_dictize
    result_dict["resources"] = resource_list_dictize(result, context)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 68, in resource_list_dictize
    resource_dict = resource_dictize(res, context)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckan/ckan/lib/dictization/model_dictize.py", line 117, in resource_dictize
    qualified=True)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckan/ckan/lib/helpers.py", line 307, in url_for
    my_url = _url_for_flask(*args, **kw)
  File "/home/martinb/workspace/ckan_master/lib/default/src/ckan/ckan/lib/helpers.py", line 366, in _url_for_flask
    my_url = _flask_default_url_for(*args, **kw)
  File "/usr/lib/ckan_master/default/local/lib/python2.7/site-packages/flask/helpers.py", line 269, in url_for
    raise RuntimeError('Attempted to generate a URL without the '
RuntimeError: Attempted to generate a URL without the application context being pushed. This has to be executed when application context is available.

```

**Comment by martinburchell** [comment]
https://github.com/ckan/ckan/issues/3760 is probably relevant

**Comment by smotornyuk** [comment]
v2.0.0 supports CKAN >= 2.9
